In [1]:
import control

In [ ]:
import jupyter_dash
from jupyter_dash import JupyterDash
from dash import Dash, html, dcc, Input, Output
import plotly.express as px
import pandas as pd

In [65]:
Gz = control.TransferFunction([1,0.4],[1, -1.2, 0.35], 2)
Gz

TransferFunction(array([1. , 0.4]), array([ 1.  , -1.2 ,  0.35]), 2)

In [8]:
control.feedback(Gz)

TransferFunction(array([1. , 0.4]), array([ 1.  , -0.2 ,  0.75]), 2)

In [56]:
T, yout = control.step_response(Gz)

In [57]:
list_of_tuples = list(zip(T, yout))

In [58]:
df = pd.DataFrame(list_of_tuples, columns = ['Tempo', 'Valor'])

In [59]:
df

Tempo     Valor
0     0.0  0.000000
1     2.0  1.000000
2     4.0  2.600000
3     6.0  4.170000
4     8.0  5.494000
5    10.0  6.533300
6    12.0  7.317060
7    14.0  7.893817
8    16.0  8.311609
9    18.0  8.611095
10   20.0  8.824251
11   22.0  8.975218
12   24.0  9.081774
13   26.0  9.156802
14   28.0  9.209542
15   30.0  9.246569
16   32.0  9.272544
17   34.0  9.290753
18   36.0  9.303513
19   38.0  9.312453

In [60]:
fig = px.line(df, x = "Tempo", y='Valor')

In [61]:
fig

In [66]:
control.poles(Gz)

array([0.7+0.j, 0.5+0.j])

In [67]:
control.zeros(Gz)

array([-0.4+0.j])

In [68]:
import math

In [74]:
tetap1 = math.pi - math.atan((0.64/0.34))

In [75]:
tetap2 = math.pi - math.atan((0.64/(0.5-0.36)))

In [76]:
tetaz1 = math.atan((0.64/(0.4+0.36)))

In [77]:
tetap1 + tetap2 -tetaz1

3.1453914346246927

In [103]:
import numpy as np

In [111]:
x = np.arange(-2,2,0.1)

In [130]:
#%matplotlib widget

In [132]:
control.rlocus(Gz);

In [100]:
out[0]

array([[ 5.00000000e-01+0.j        ,  7.00000000e-01+0.j        ],
       [ 5.12171523e-01+0.j        ,  6.85322196e-01+0.j        ],
       [ 5.26827471e-01+0.j        ,  6.68159966e-01+0.j        ],
       [ 5.46287711e-01+0.j        ,  6.46193445e-01+0.j        ],
       [ 5.94987437e-01+0.j        ,  5.94987437e-01+0.j        ],
       [ 5.93139874e-01-0.06060686j,  5.93139874e-01+0.06060686j],
       [ 5.91292310e-01-0.08567121j,  5.91292310e-01+0.08567121j],
       [ 5.89444747e-01-0.10487656j,  5.89444747e-01+0.10487656j],
       [ 5.87597184e-01-0.12104463j,  5.87597184e-01+0.12104463j],
       [ 5.80206930e-01-0.17086361j,  5.80206930e-01+0.17086361j],
       [ 5.72816677e-01-0.20887248j,  5.72816677e-01+0.20887248j],
       [ 5.65426423e-01-0.24073185j,  5.65426423e-01+0.24073185j],
       [ 5.58036170e-01-0.2686386j ,  5.58036170e-01+0.2686386j ],
       [ 5.50645916e-01-0.29372154j,  5.50645916e-01+0.29372154j],
       [ 5.43255663e-01-0.31665242j,  5.43255663e-01+0.3166524